// "use client"
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
// import Link from "next/link"; // Uncommented this line
import MainNavbar from "@/components/Common/Navbar";
import Footer from "@/components/Common/Footer";
import MainProvider from '@/Provider/MainProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <MainProvider>
          <MainNavbar />
          {children}
          <Footer/>
        </MainProvider>

      </body>
    </html >
  );
}